spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.122:3306/wk_move
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    database: mysql
    open-in-view: true

  jackson:
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_empty

server:
  servlet:
    context-path: /api
  port: 8091